[package]
name = "imhm"
version = "0.1.0"
edition = "2024"
authors = ["Eric Stokes <eestokes@pm.me>"]
publish = true
description = "A fast immutable hashmap"
categories = ["data-structures"]
keywords = ["map", "set", "immutable", "persistent", "functional"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/imhm"
repository = "https://github.com/estokes/imhm"

[dependencies]
anyhow = "1"
rustc-hash = "2"
triomphe = "0.1.16"

[dev-dependencies]
ahash = "0.8"
arcstr = "1"
compact_str = "0.9"
imbl = "7"
immutable-chunkmap = { version = "2.1.4", features = ["pool"] }
nohash = "0.2"
